
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action ExitAction;
	
	private global::Gtk.Action RunApplicationAction;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.VPaned vpaned2;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Label LblInfo;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label LblQuest1;
	
	private global::Gtk.TextView TxtLoopVal1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label LblLoopVal2;
	
	private global::Gtk.TextView TxtLoopVal2;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.ProgressBar PrgBar1;
	
	private global::Gtk.ProgressBar PrgBar2;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Button btnRun;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.RunApplicationAction = new global::Gtk.Action ("RunApplicationAction", global::Mono.Unix.Catalog.GetString ("Run Application"), null, null);
		this.RunApplicationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Run Application");
		w1.Add (this.RunApplicationAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vpaned2 = new global::Gtk.VPaned ();
		this.vpaned2.CanFocus = true;
		this.vpaned2.Name = "vpaned2";
		this.vpaned2.Position = 10;
		// Container child vpaned2.Gtk.Paned+PanedChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='ExitAction' action='ExitAction'/><menu name='RunApplicationAction' action='RunApplicationAction'/><menu name='AboutAction' action='AboutAction'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.LblInfo = new global::Gtk.Label ();
		this.LblInfo.Name = "LblInfo";
		this.LblInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("Please Input your Looping value ?");
		this.vbox1.Add (this.LblInfo);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.LblInfo]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.LblQuest1 = new global::Gtk.Label ();
		this.LblQuest1.Name = "LblQuest1";
		this.LblQuest1.LabelProp = global::Mono.Unix.Catalog.GetString ("Looping 1 value : ");
		this.hbox1.Add (this.LblQuest1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.LblQuest1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.TxtLoopVal1 = new global::Gtk.TextView ();
		this.TxtLoopVal1.CanFocus = true;
		this.TxtLoopVal1.Name = "TxtLoopVal1";
		this.TxtLoopVal1.WrapMode = ((global::Gtk.WrapMode)(2));
		this.hbox1.Add (this.TxtLoopVal1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.TxtLoopVal1]));
		w5.Position = 1;
		this.vbox3.Add (this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.LblLoopVal2 = new global::Gtk.Label ();
		this.LblLoopVal2.Name = "LblLoopVal2";
		this.LblLoopVal2.LabelProp = global::Mono.Unix.Catalog.GetString ("Looping value 2 :");
		this.hbox2.Add (this.LblLoopVal2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.LblLoopVal2]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.TxtLoopVal2 = new global::Gtk.TextView ();
		this.TxtLoopVal2.CanFocus = true;
		this.TxtLoopVal2.Name = "TxtLoopVal2";
		this.hbox2.Add (this.TxtLoopVal2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.TxtLoopVal2]));
		w8.Position = 1;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.PrgBar1 = new global::Gtk.ProgressBar ();
		this.PrgBar1.Name = "PrgBar1";
		this.PrgBar1.Fraction = 1;
		this.PrgBar1.PulseStep = 1;
		this.vbox2.Add (this.PrgBar1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.PrgBar1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.PrgBar2 = new global::Gtk.ProgressBar ();
		this.PrgBar2.Name = "PrgBar2";
		this.PrgBar2.Fraction = 1;
		this.PrgBar2.PulseStep = 1;
		this.vbox2.Add (this.PrgBar2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.PrgBar2]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnRun = new global::Gtk.Button ();
		this.btnRun.CanFocus = true;
		this.btnRun.Name = "btnRun";
		this.btnRun.UseUnderline = true;
		this.btnRun.Label = global::Mono.Unix.Catalog.GetString ("Run Progress Bar");
		this.hbox3.Add (this.btnRun);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnRun]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox3.Add (this.vbox2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox2]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.vpaned2.Add (this.vbox1);
		this.Add (this.vpaned2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 463;
		this.DefaultHeight = 188;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ExitAction.Activated += new global::System.EventHandler (this.OnExitActionActivated);
		this.RunApplicationAction.Activated += new global::System.EventHandler (this.OnRunApplicationActionActivated);
		this.btnRun.Clicked += new global::System.EventHandler (this.OnBtnRunClicked);
	}
}
